name: wiki

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sync_docs:
    name: Sync docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
      - name: Sync with local action
        uses: kai-tub/external-repo-sync-action@v1
        with:
          source-directory: "./docs"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
